baseURL = "https://yamamon.page/"
languageCode = "ja"
title = "Yamamon's web."
theme = "minimal"
googleAnalytics = "G-NC0YDQZZLH"

[params]
    author = "Shoya Yamamoto"
    description = "フリーランスエンジニア 山元彰也のwebサイトです。"
    githubUsername = "S-Yamamoto3215"
    accent = "#23466e"
    showBorder = true
    backgroundColor = "#f4f5f7"
    font = "M Plus 1p"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["ruby", "html", "css", "javascript", "rails"]
    copyright = "&copy; Shoya Yamamoto."

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

# [[menu.main]]
#     url = "/blog/"
#     name = "Blogs"
#     weight = 3

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:yamamotoshoya8@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/S-Yamamoto3215/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/ShoyaYamamoto3215/"
    name = "facebook"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/yamamon_zawawa/"
    name = "twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/yamamoto_shoya/"
    name = "instagram"
    weight = 5
