baseURL = "https://yamamon.page/"
defaultContentLanguage = "ja"
enableEmoji = true
enableRobotsTXT = true
languageCode = "ja"
pygmentsStyle = "monokai"
theme = "gokarna"
title = "Shoya Yamamoto"

[params]
  accentColor = "#FF4D4D"
  avatarAltText = "Shoya Yamamoto"
  avatarSize = "size-s"
  avatarURL = "/images/avatar.jpg"
  customHeadHTML = ""
  dateFormat = "2006 / 01 / 02"
  description = "Freelance engineer Shoya Yamamoto's website."
  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 4
  fontSize = "16px"
  footer = "Shoya Yamamoto."
  togglePreviousAndNextButtons = true
  displayReadingTime = true
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true

  socialIcons = [
    {name = "twitter", url = "https://twitter.com/yamamon_zawawa/"},
    {name = "instagram", url = "https://www.instagram.com/yamamoto_shoya/"},
    {name = "email", url = "mailto:yamamotoshoya8@gmail.com"},
    {name = "facebook", url = "https://www.facebook.com/ShoyaYamamoto3215/"},
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Career"
    pre = "<span data-feather='award'></span>"
    url = "/career/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/S-Yamamoto3215/"
    weight = 6

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
  minifyOutput = true
